sudo: false
language: elixir
elixir:
  - 1.4.4
otp_release:
  - 19.1

addons:
  postgresql: '9.4'
services:
  - postgresql

cache:
  directories:
    - _build
    - deps

branches:
  only:
    - master
